#!/bin/bash
TARGET_DEFCONFIG="common/arch/arm64/configs/gki_defconfig"

if [ -f "$TARGET_DEFCONFIG" ]; then
    echo "Appending Docker and Container flags directly into $TARGET_DEFCONFIG..."
    cat << 'DOCKER_CONF' >> "$TARGET_DEFCONFIG"

# --- CORE CONTAINER & DOCKER RUNTIME HEADLESS OPTIONS ---
CONFIG_NAMESPACES=y
CONFIG_UTS_NS=y
CONFIG_IPC_NS=y
CONFIG_USER_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_CGROUPS=y
CONFIG_MEMCG=y
CONFIG_CGROUP_SCHED=y
CONFIG_CGROUP_PIDS=y
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CPUSETS=y
CONFIG_BRIDGE=y
CONFIG_BRIDGE_NETFILTER=y
CONFIG_VETH=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_MASQUERADE=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NETFILTER=y
CONFIG_NF_NAT=y
CONFIG_SECCOMP=y
CONFIG_BLK_DEV_DM=y
CONFIG_OVERLAY_FS=y
DOCKER_CONF
    echo "Configuration patch applied successfully."
else
    echo "Error: Target configuration baseline file not found at $TARGET_DEFCONFIG!"
    exit 1
fi
